env:
  node: true
  commonjs: true
  es6: true
  jest: true

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings

settings:
  import/resolver: node

rules:
  no-console:
    - off
  no-mixed-requires:
    - error
  no-var:
    - error
  prefer-const:
    - error
  indent:
    - error
    - 2
  block-spacing:
    - warn
    - always
  comma-dangle:
    - warn
    - always-multiline
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  max-len:
    - error
    - { code: 100 }
  import/no-unresolved:
    - error
    - { commonjs: true, amd: true }
